:toc:

== Setup Smart Contract

1. install rust using below command

.. curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
.. rustup default stable
.. rustup target add wasm32-unknown-unknown

2. install cargo-generate require for bootstrapping new Cosmwasm smart contract

.. cargo install cargo-generate --features vendored-openssl

3. install cargo-run-script to optimize the smart contract

.. cargo install cargo-run-script

4. To write the small smart contract, can follow below terra docs

    https://docs.terra.money/Tutorials/Smart-contracts/Write-smart-contract.html#start-with-a-template

    Note:: This terra docs smart contract is in old version, update the version of cosmwasm libraries in rust.toml file

5. To compile the smart contract, run the below command inside the smart contract directory

    cargo wasm

6. Before deploying the smart contract, optimize the smart contract using below command

    docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.4

7. verify the .wasm file created in the artifacts directory.

== Deploy and Running Smart Contract on Comdex Chain

1. Set below variables before deploying

    export RPC="http://127.0.0.1:26657"
    export NODE=(--node $RPC)
    export CHAIN_ID=my-chain
    export TXFLAG=($NODE --chain-id $CHAIN_ID --gas-prices 0.025validatortoken --gas auto --gas-adjustment 1.3)

2. To Deploy smart contract use below command

    comdex tx wasm store artifacts/my_first_contract.wasm --from my-account $TXFLAG -y --output json

3. To Instantiate the smart contract use below command

    comdex tx wasm instantiate 1 '{"count":0}' --from my-account $TXFLAG -y

4. To execute the smart contract use below command

    comdex tx wasm execute comdex18vd8fpwxzck93qlwghaj6arh4p7c5n89md6mqr '{"increment":{}}' --from my-account $TXFLAG -y

5. To query the smart contract use below command

    comdex query wasm contract-store comdex18vd8fpwxzck93qlwghaj6arh4p7c5n89md6mqr '{"get_count":{}}'

6. In app.toml file add below configuration

    [wasm]
    # The maximum gas amount can be spent for contract query.
    # The contract query will invoke contract execution vm,
    # so we need to restrict the max usage to prevent DoS attack
    contract-query-gas-limit = "3000000"
    # The flag to specify whether print contract logs or not
    contract-debug-mode = "false"
    # The WASM VM memory cache size in MiB not bytes
    contract-memory-cache-size = "100"

*Note* contract_address = comdex18vd8fpwxzck93qlwghaj6arh4p7c5n89md6mqr -


